### ISSUE TITLE
EasyScape 

### ISSUE THREAD

**Issue by RobertDell** [alanbaumgartner/Easyscape#12]
EDIT: sorry. meant to make this a PR.
 have a question about the easyscape plugin. is it possible to emulate the functionality of that plugin to work for deleting menu options for players too (in addition to objects/examine)? How difficult would that be to implement given the existing framework for the plugin as it stands? The reason i'm asking is because i've noticed in populated areas using items on stuff can be kind of a nuisance. It'd be a nice little qol thing and i'm willing to learn how to do it myself but just looking for a little guidance on how to add this feature. 
![image](https://user-images.githubusercontent.com/50180884/57034205-c8bc5c00-6c03-11e9-8e0d-8c236e4bf846.png)

**Comment by alanbaumgartner** [comment]
Yea, it is for sure possible.

I can look into it this weekend (end of semester is coming up) but if you want to try it yourself, when the plugin gets the MenuEntry list, check if the MenuEntry's target is a player, if so remove it. I remove some MenuEntry using ArrayUtil so there is an example for that, as for how to check if a player is the target, I am not sure yet.

**Comment by RobertDell** [comment]
Alright thanks for responding. I'm also going through the tail end of finals now but if I do get a chance I'll look into it and see what I get. Thanks for the advice

**Comment by RobertDell** [comment]
Looked over it a little bit. What did you mean by when the plugin gets to the menu entry list?

**Comment by alanbaumgartner** [comment]
https://github.com/alanbaumgartner/Easyscape/blob/90aef6acdd676f3ebb21811234dab9be1bbf01f4/easy/swap/EasySwapPlugin.java#L79

This is where the plugin gets the menu entry list, and stores them in the swapper object.

**Comment by RobertDell** [comment]
Yeah, not sure how to check if the player is a target. Have you had any luck with that?

**Comment by alanbaumgartner** [comment]
I plan to take a look at it tonight, if all goes well I can add it in and also fix #11 too.

**Comment by RobertDell** [comment]
Okay nice. Would you happen to have an ETA? If not, no worries. Thank you!!

**Comment by RobertDell** [comment]
Hi, just wondering if you are still working on this. If there's any way I can help, please let me know.

**Comment by alanbaumgartner** [comment]
Yep, should be out tomorrow or the next. sorry for the wait

**Comment by RobertDell** [comment]
No problem. Looking forward to seeing how you pulled it off :D thanks again Alan.

**Comment by RobertDell** [comment]
Hi. Not sure if you've already uploaded it, I didn't see a change in the code. Sorry to bother.

**Comment by RobertDell** [comment]
Let me know when you can.

**Comment by alanbaumgartner** [comment]
I am most likely not going to be updating this anymore. I no longer play and I also have a full time job. I am accepting pull requests if anyone wants to fix this.

**Comment by alanbaumgartner** [comment]
If you are still looking for the functionality of this plugin, I would recommend checking out this project. https://github.com/runelite-extended/runelite

It seems at some point they updated Easyscape on themselves and then moved the functionality between different plugins to reduce clutter. Looks like a cool project!
