### ISSUE TITLE
Possible to add remove item in construction build mode

### ISSUE THREAD

**Issue by kgbeast7** [alanbaumgartner/Easyscape#3]
Would it be possible to add a left-click remove item similar to the left-click build item?

**Comment by alanbaumgartner** [comment]
I actually have an update for this that i haven't put on github yet. Also I have pretty bad wording with the config. In the update, the left click build item will include the left click remove. Ill update it in about an hour.

**Comment by alanbaumgartner** [comment]
Fixed in the latest commit!
