### ISSUE TITLE
New Commit broke easy construction plugin

### ISSUE THREAD

**Issue by kgbeast7** [alanbaumgartner/Easyscape#4]
The commit that you added for the 'remove' left click function seems to have broken the easy construction plugin. 

[Screenshot](https://i.imgur.com/HQXjMr7.png)

**Comment by alanbaumgartner** [comment]
It seems the region ID for peoples houses might be different depending on the player, as a temporary fix, delete "&& isHouse()" check on line 121.

**Comment by alanbaumgartner** [comment]
When you get a chance, can you enable the developer mode of runelite and turn on the option called "Location" for me and send me the screenshot?

**Comment by kgbeast7** [comment]
Here you go https://i.imgur.com/DHKL5kX.png
