### ISSUE TITLE
I have this error

### ISSUE THREAD

**Issue by PBread07** [alanbaumgartner/Easyscape#5]
http://prntscr.com/mtu6x1

**Comment by alanbaumgartner** [comment]
The casing is wrong on either the file or the class name, notice in the filename its Easy"S"cape and in the class definition its Easy"s"cape. change the filename or the class definition and it should fix it.

**Comment by PBread07** [comment]
Could you send a screenie of what ones I am meant to change please. This is my current view. http://prntscr.com/mtur7b

**Comment by alanbaumgartner** [comment]
on line 45 of your screenshot, capitalize the S in scape. I also have an update that changes much of the code coming out within the next week which changes a lot.
