### ISSUE TITLE
Last Update broke

### ISSUE THREAD

**Issue by Menddd** [alanbaumgartner/Easyscape#6]
n.runelite.client.eventbus.EventBus - Uncaught exception in event subscriber
java.lang.ArrayIndexOutOfBoundsException: null

**Comment by alanbaumgartner** [comment]
This doesn't tell me anything.

**Comment by Menddd** [comment]
https://i.imgur.com/Jy9w6Lf.png (had to rename it because I already have a plugin named the same) 

Pretty much it spams this when clicking build and then you can't press x afterwards without turning off the plugin I removed the other plugin and tried your stock file to the same affect

**Comment by alanbaumgartner** [comment]
ahh okay, i have a big update coming soon so I am probably not going to fix this as its not present in my latest build. This is when youre doing construction right? What does "x" mean? The top right x or the button on your keyboard?

**Comment by Menddd** [comment]
Yes, construction, and the x to close the interface because the client hangs until you turn the plugin off

**Comment by alanbaumgartner** [comment]
hmm, very weird, might have been the update today that broke it since the x shouldnt mess with anything. Ill look at it sometime and post back
